# Copyright 2025 The android_world Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tier 4 tasks for Markor - ADB-exclusive."""

import datetime
import random
from typing import Any

from android_world.env import adb_utils
from android_world.env import interface
from android_world.task_evals import task_eval
from android_world.utils import file_utils

_MARKOR_DIR = "/storage/emulated/0/Documents/Markor"
_MARKOR_NOTES_DIR = f"{_MARKOR_DIR}/Notes"
_FOOTER = "---\nGenerated by AutoBot"


class Tier4BulkAppendFooterToMarkdown(task_eval.TaskEval):
  """Append footer to every .md file in Markor Notes folder. ADB-exclusive."""

  app_names = ("markor",)
  complexity = 1.5
  schema = {"type": "object", "properties": {}, "required": []}
  template = (
      "Append the following text to every .md file in the 'Notes' folder in"
      " Markor (/storage/emulated/0/Documents/Markor/Notes/):\n"
      "---\nGenerated by AutoBot"
  )

  def initialize_task(self, env: interface.AsyncEnv) -> None:
    super().initialize_task(env)
    adb_utils.issue_generic_request(
        ["shell", "mkdir", "-p", _MARKOR_NOTES_DIR], env.controller
    )
    adb_utils.issue_generic_request(
        ["shell", "find", _MARKOR_NOTES_DIR, "-name", "note_*.md", "-delete"],
        env.controller,
    )
    self._filenames: list[str] = []
    for i in range(random.randint(3, 5)):
      name = f"note_{random.randint(1000, 9999)}.md"
      content = f"# Note {i}\n\nSome content here."
      file_utils.create_file(name, _MARKOR_NOTES_DIR, env.controller, content=content)
      self._filenames.append(name)

  def tear_down(self, env: interface.AsyncEnv) -> None:
    for name in self._filenames:
      adb_utils.issue_generic_request(
          ["shell", "rm", "-f", f"{_MARKOR_NOTES_DIR}/{name}"], env.controller
      )
    super().tear_down(env)

  def is_successful(self, env: interface.AsyncEnv) -> float:
    super().is_successful(env)
    for name in self._filenames:
      res = adb_utils.issue_generic_request(
          ["shell", "tail", "-2", f"{_MARKOR_NOTES_DIR}/{name}"], env.controller
      )
      if "Generated by AutoBot" not in res.generic.output.decode():
        return 0.0
    return 1.0

  @classmethod
  def generate_random_params(cls) -> dict[str, Any]:
    return {}


class Tier4AggregationLongestMarkorNote(task_eval.TaskEval):
  """Which Markor note has the most content by character count? ADB-exclusive."""

  app_names = ("markor",)
  complexity = 1.2
  schema = {"type": "object", "properties": {}, "required": []}
  template = (
      "Which note in the Markor folder"
      " (/storage/emulated/0/Documents/Markor/) has the most content by"
      " character count? Output the filename."
  )

  def initialize_task(self, env: interface.AsyncEnv) -> None:
    super().initialize_task(env)
    adb_utils.issue_generic_request(
        ["shell", "mkdir", "-p", _MARKOR_DIR], env.controller
    )
    adb_utils.issue_generic_request(
        ["shell", "find", _MARKOR_DIR, "-maxdepth", "1", "-name",
         "longtest_*.md", "-delete"],
        env.controller,
    )
    sizes = [random.randint(50, 200) for _ in range(4)]
    sizes.append(random.randint(500, 1000))  # One clearly longest
    random.shuffle(sizes)
    named_sizes: list[tuple[str, int]] = []
    for size in sizes:
      name = f"longtest_{random.randint(1000, 9999)}.md"
      file_utils.create_file(
          name, _MARKOR_DIR, env.controller, content="x" * size
      )
      named_sizes.append((name, size))
    self._ground_truth: str = max(named_sizes, key=lambda x: x[1])[0]
    self._filenames: list[str] = [name for name, _ in named_sizes]

  def tear_down(self, env: interface.AsyncEnv) -> None:
    for name in self._filenames:
      adb_utils.issue_generic_request(
          ["shell", "rm", "-f", f"{_MARKOR_DIR}/{name}"], env.controller
      )
    super().tear_down(env)

  def is_successful(self, env: interface.AsyncEnv) -> float:
    super().is_successful(env)
    cache = getattr(env, "interaction_cache", "") or ""
    return 1.0 if self._ground_truth in cache else 0.0

  @classmethod
  def generate_random_params(cls) -> dict[str, Any]:
    return {}


class Tier4TopKMarkorMostModifiedNotes(task_eval.TaskEval):
  """Which 5 Markor notes were modified most recently in last 7 days? ADB-exclusive."""

  app_names = ("markor",)
  complexity = 1.5
  schema = {"type": "object", "properties": {}, "required": []}
  template = (
      "Which 5 notes in Markor (/storage/emulated/0/Documents/Markor/) were"
      " modified most recently in the last 7 days? List the filenames."
  )

  def initialize_task(self, env: interface.AsyncEnv) -> None:
    super().initialize_task(env)
    adb_utils.issue_generic_request(
        ["shell", "mkdir", "-p", _MARKOR_DIR], env.controller
    )
    adb_utils.issue_generic_request(
        ["shell", "find", _MARKOR_DIR, "-maxdepth", "1", "-name",
         "recent_*.md", "-delete"],
        env.controller,
    )
    # 7 notes: offsets in days from now (all within 7 days, varying recency)
    offsets = [0.5, 1.2, 2.3, 3.5, 4.1, 5.0, 6.4]
    random.shuffle(offsets)
    now = datetime.datetime.now()
    named_offsets: list[tuple[str, float]] = []
    self._filenames: list[str] = []
    for offset in offsets:
      name = f"recent_{random.randint(1000, 9999)}.md"
      dt = now - datetime.timedelta(days=offset)
      file_utils.create_file(name, _MARKOR_DIR, env.controller, content="content")
      touch_ts = dt.strftime("%Y%m%d%H%M.%S")
      adb_utils.issue_generic_request(
          ["shell", "touch", "-t", touch_ts, f"{_MARKOR_DIR}/{name}"],
          env.controller,
      )
      self._filenames.append(name)
      named_offsets.append((name, offset))
    # Top 5 = smallest offset (most recent)
    named_offsets.sort(key=lambda x: x[1])
    self._ground_truth: list[str] = [name for name, _ in named_offsets[:5]]

  def tear_down(self, env: interface.AsyncEnv) -> None:
    for name in self._filenames:
      adb_utils.issue_generic_request(
          ["shell", "rm", "-f", f"{_MARKOR_DIR}/{name}"], env.controller
      )
    super().tear_down(env)

  def is_successful(self, env: interface.AsyncEnv) -> float:
    super().is_successful(env)
    cache = getattr(env, "interaction_cache", "") or ""
    for name in self._ground_truth:
      if name not in cache:
        return 0.0
    return 1.0

  @classmethod
  def generate_random_params(cls) -> dict[str, Any]:
    return {}
